# Huymaier Console GitHub release updater integration.
$script:ConsoleUpdateStatePath = Join-Path $script:DataDir 'console-update-state.json'
$script:ConsoleUpdateState = $null
$script:ConsoleUpdateStateSignature = ''
$script:ConsoleUpdateWorkerPath = Join-Path $script:BaseDir 'HuymaierConsoleUpdateWorker.ps1'
$script:ConsoleApplyUpdatePath = Join-Path $script:BaseDir 'HuymaierConsoleApplyUpdate.ps1'
function New-DefaultConsoleUpdateState {[pscustomobject]@{Phase='Idle';Message='Check GitHub for a newer Huymaier Console release.';Busy=$false;CurrentVersion=$script:AppVersion;LatestVersion='';UpdateAvailable=$false;ReleaseName='';ReleaseNotes='';PublishedAt='';AssetName='';AssetSize=0L;DownloadedBytes=0L;DownloadPercent=0;Verified=$false;PackagePath='';Error='';Repository='thermalkil/HuymaierConsole'}}
function Read-ConsoleUpdateState {if(-not(Test-Path -LiteralPath $script:ConsoleUpdateStatePath)){if($null -eq $script:ConsoleUpdateState){$script:ConsoleUpdateState=New-DefaultConsoleUpdateState};return $script:ConsoleUpdateState};try{$script:ConsoleUpdateState=Get-Content -Raw -LiteralPath $script:ConsoleUpdateStatePath|ConvertFrom-Json}catch{$script:ConsoleUpdateState=New-DefaultConsoleUpdateState};return $script:ConsoleUpdateState}
function Start-ConsoleUpdateWorker {param([ValidateSet('Scan','Download')][string]$Action);Read-ConsoleUpdateState|Out-Null;if([bool](Get-EntryProperty $script:ConsoleUpdateState 'Busy' $false)){return};if(-not(Test-Path -LiteralPath $script:ConsoleUpdateWorkerPath)){Set-ConsoleNotice 'Huymaier Console update worker is missing.' 'ERROR';return};$args=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$script:ConsoleUpdateWorkerPath,'-Action',$Action,'-StatePath',$script:ConsoleUpdateStatePath,'-CurrentVersion',$script:AppVersion,'-Repository','thermalkil/HuymaierConsole','-InstallRoot',$script:BaseDir);try{Start-Process powershell.exe -ArgumentList $args -WindowStyle Hidden|Out-Null;$script:ConsoleUpdateState=New-DefaultConsoleUpdateState;$script:ConsoleUpdateState.Phase=if($Action -eq 'Scan'){'Scanning'}else{'Downloading'};$script:ConsoleUpdateState.Message=if($Action -eq 'Scan'){'Checking GitHub Releases...'}else{'Downloading the latest verified release...'};$script:ConsoleUpdateState.Busy=$true;Write-Log "Huymaier Console update worker requested: Action=$Action";Render-Page}catch{Set-ConsoleNotice "Huymaier Console update could not start: $($_.Exception.Message)" 'ERROR'}}
function Start-ConsoleUpdateApply {Read-ConsoleUpdateState|Out-Null;$pkg=[string](Get-EntryProperty $script:ConsoleUpdateState 'PackagePath' '');if(-not [bool](Get-EntryProperty $script:ConsoleUpdateState 'Verified' $false) -or -not(Test-Path -LiteralPath $pkg)){Set-ConsoleNotice 'Download and verify the update first.' 'WARN';return};if(-not(Test-Path -LiteralPath $script:ConsoleApplyUpdatePath)){Set-ConsoleNotice 'Huymaier Console update apply helper is missing.' 'ERROR';return};$args=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$script:ConsoleApplyUpdatePath,'-PackagePath',$pkg,'-InstallRoot',$script:BaseDir,'-ConsoleProcessId',$PID);Start-Process powershell.exe -ArgumentList $args -WindowStyle Hidden|Out-Null;Write-Log 'Verified Huymaier Console update handed to apply helper; closing current process.';$script:AllowWindowClose=$true;$script:Window.Close()}
function Get-ConsoleUpdateHeroText {Read-ConsoleUpdateState|Out-Null;$s=$script:ConsoleUpdateState;$parts=New-Object System.Collections.Generic.List[string];$parts.Add("Installed: v$script:AppVersion");$latest=[string](Get-EntryProperty $s 'LatestVersion' '');if($latest){$parts.Add("Latest: v$latest")};$m=[string](Get-EntryProperty $s 'Message' '');if($m){$parts.Add($m)};return($parts -join "`n")}
