param(
    [ValidateSet('Scan','Download')][string]$Action='Scan',
    [Parameter(Mandatory=$true)][string]$StatePath,
    [Parameter(Mandatory=$true)][string]$CurrentVersion,
    [string]$Repository='thermalkil/HuymaierConsole',
    [Parameter(Mandatory=$true)][string]$InstallRoot
)
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
function Write-State([string]$Phase,[string]$Message,[bool]$Busy,[hashtable]$Extra=@{}){$o=[ordered]@{Phase=$Phase;Message=$Message;Busy=$Busy;CurrentVersion=$CurrentVersion;LatestVersion='';UpdateAvailable=$false;ReleaseName='';ReleaseNotes='';PublishedAt='';AssetName='';AssetSize=0L;DownloadedBytes=0L;DownloadPercent=0;Verified=$false;PackagePath='';Error='';Repository=$Repository};foreach($k in $Extra.Keys){$o[$k]=$Extra[$k]};$dir=Split-Path -Parent $StatePath;if($dir){New-Item -ItemType Directory -Force -Path $dir|Out-Null};[pscustomobject]$o|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $StatePath -Encoding UTF8}
function Get-GitHubToken {foreach($name in @('HUYMAIER_GITHUB_TOKEN','GITHUB_TOKEN')){try{$v=[Environment]::GetEnvironmentVariable($name);if($v){return $v}}catch{}};try{if(Get-Command gh -ErrorAction SilentlyContinue){$t=(& gh auth token 2>$null);if($LASTEXITCODE -eq 0 -and $t){return [string]$t.Trim()}}}catch{};return ''}
function Get-Headers([string]$Token,[string]$Accept='application/vnd.github+json'){$h=@{'Accept'=$Accept;'User-Agent'='HuymaierConsole-Updater';'X-GitHub-Api-Version'='2022-11-28'};if($Token){$h['Authorization']="Bearer $Token"};return $h}
function Get-LatestRelease([string]$Token){Invoke-RestMethod -Uri "https://api.github.com/repos/$Repository/releases/latest" -Headers (Get-Headers $Token) -Method Get -UseBasicParsing}
function Get-Version([string]$Text){$v=([string]$Text).Trim();$v=$v -replace '^[vV]','';try{return [version]$v}catch{return [version]'0.0.0'}}
function Get-PackageAsset($Release){$z=@($Release.assets|Where-Object{[string]$_.name -match '(?i)\.zip$' -and [string]$_.name -notmatch '(?i)(source|src|symbols)'});if($z.Count -eq 0){throw 'The release does not contain an installable ZIP asset.'};return($z|Sort-Object size -Descending|Select-Object -First 1)}
function Get-ChecksumAsset($Release,[string]$ZipName){$base=[IO.Path]::GetFileNameWithoutExtension($ZipName);return @($Release.assets|Where-Object{[string]$_.name -in @("$ZipName.sha256","$base.sha256","SHA256SUMS.txt","checksums.sha256")}|Select-Object -First 1)}
function Download-Asset($Asset,[string]$Destination,[string]$Token){$headers=Get-Headers $Token 'application/octet-stream';$uri=if($Token -and $Asset.url){[string]$Asset.url}else{[string]$Asset.browser_download_url};Invoke-WebRequest -Uri $uri -Headers $headers -OutFile $Destination -UseBasicParsing}
function Resolve-ExpectedHash([string]$Text,[string]$ZipName){foreach($line in ($Text -split "`r?`n")){if($line -match '(?i)^\s*([0-9a-f]{64})\s+\*?(.+?)\s*$'){if(([IO.Path]::GetFileName($matches[2])) -ieq $ZipName){return $matches[1].ToLowerInvariant()}}elseif($line -match '(?i)^\s*([0-9a-f]{64})\s*$'){return $matches[1].ToLowerInvariant()}};return ''}
try{Write-State 'Scanning' 'Checking GitHub Releases...' $true;$token=Get-GitHubToken;$release=Get-LatestRelease $token;$latestText=[string]$release.tag_name;if(-not $latestText){$latestText=[string]$release.name};$latest=Get-Version $latestText;$current=Get-Version $CurrentVersion;$available=$latest -gt $current;$asset=Get-PackageAsset $release;$common=@{LatestVersion=$latest.ToString();UpdateAvailable=$available;ReleaseName=[string]$release.name;ReleaseNotes=[string]$release.body;PublishedAt=[string]$release.published_at;AssetName=[string]$asset.name;AssetSize=[long]$asset.size};if($Action -eq 'Scan'){if($available){Write-State 'UpdateAvailable' "Huymaier Console v$latest is available." $false $common}else{Write-State 'UpToDate' 'Huymaier Console is up to date.' $false $common};exit 0};if(-not $available){Write-State 'UpToDate' 'Huymaier Console is already up to date.' $false $common;exit 0};$updateDir=Join-Path (Split-Path -Parent $StatePath) 'Updates';New-Item -ItemType Directory -Force -Path $updateDir|Out-Null;$zipPath=Join-Path $updateDir ([string]$asset.name);$common.PackagePath=$zipPath;Write-State 'Downloading' "Downloading $($asset.name)..." $true $common;Download-Asset $asset $zipPath $token;$common.DownloadedBytes=(Get-Item -LiteralPath $zipPath).Length;$common.DownloadPercent=100;$checksum=Get-ChecksumAsset $release ([string]$asset.name);if($null -eq $checksum){throw 'Release checksum asset is missing. Refusing to install an unverified update.'};$checksumPath=Join-Path $updateDir ([string]$checksum.name);Download-Asset $checksum $checksumPath $token;$expected=Resolve-ExpectedHash (Get-Content -Raw -LiteralPath $checksumPath) ([string]$asset.name);if(-not $expected){throw 'Could not find the release ZIP SHA-256 in the checksum asset.'};$actual=(Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash.ToLowerInvariant();if($actual -ne $expected){throw "SHA-256 verification failed. Expected $expected but downloaded $actual."};$common.Verified=$true;Write-State 'ReadyToInstall' 'Download verified. Choose Install and restart Huymaier Console.' $false $common}catch{Write-State 'Error' $_.Exception.Message $false @{Error=$_.Exception.Message};exit 1}
