Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$runtime=Join-Path $root 'HuymaierUser3DModels.ps1';$live=Join-Path $root 'HuymaierLivePlatformModels.ps1';$loader=Join-Path $root 'Native\HuymaierModelPreviewWorker.cs';$control=Join-Path $root 'Native\HuymaierLiveModelControl.cs';$optimizer=Join-Path $root '.build\Optimize-User3DModels.ps1';$sourceList=Join-Path $root '.source\source-files.txt'
foreach($p in @($runtime,$live,$loader,$control,$optimizer,$sourceList)){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "V6 3D shelf source missing: $p"}}
foreach($ps in @($runtime,$live,$optimizer)){$t=$null;$e=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($ps,[ref]$t,[ref]$e);if(@($e).Count){throw "$ps failed Windows PowerShell 5.1 parse: $(@($e|ForEach-Object{$_.Message}) -join '; ')"};foreach($v in @($ast.FindAll({param($n)$n -is [Management.Automation.Language.VariableExpressionAst]},$true))){if([string]::Equals([string]$v.VariablePath.UserPath,'Host',[StringComparison]::OrdinalIgnoreCase)){throw "Active 3D runtime references reserved `$Host: $ps line $($v.Extent.StartLineNumber)"}}}
$text=Get-Content -Raw $runtime -Encoding UTF8
function Need([string]$n){if($text.IndexOf($n,[StringComparison]::Ordinal)-lt0){throw "V6 3D shelf contract missing: $n"}}
function Reject([string]$n){if($text.IndexOf($n,[StringComparison]::Ordinal)-ge0){throw "Retired/oversized 3D presentation survived V6: $n"}}
foreach($n in @('HUYMAIER_USER_3D_MODELS_RUNTIME_V6','HUYMAIER_3D_DUAL_SHELF_RUNTIME_V1','HUYMAIER_3D_TEXTURED_BOUNDED_RESIDENCY_V2',"Join-Path `$script:DataDir '3D Models'",'README - Model Names.txt','Get-HcDetectedUser3DModelCount',"`$script:SubPage-ne'Customization'",'Platform visuals: ','Icon card size','3D shelf model size','3D Models Folder - ','Add-Hc3DShelfGroup','Add-Hc3DPlatformShelf','Test-HcStorefrontPlatform',"Add-Hc3DShelfGroup 'Providers' 'Providers'","Add-Hc3DShelfGroup 'Consoles' 'Consoles'",'maxTextureResidency=4','New-Hc3DShelfLiveModelView','Test-Hc3DCardShouldStayResident','Trim-Hc3DShelfResidency','Queue-Hc3DShelfNeighborhood','Start-Hc3DShelfSpinTimer','Deferred redundant Games 3D shelf rebuild')){Need $n}
foreach($n in @('$card.Button.Width=470','$card.Button.Height=390','$card.VisualHost.Height=302','textureResidency=3','HcUser3DCardQueue','Queue-HcUser3DCard','Set-HcAtlasFallbackVisual')){Reject $n}
foreach($n in @('$card.Button.Width=$(if($groupFocused){286}else{236})','$card.Button.Height=$(if($groupFocused){178}else{156})','$card.VisualHost.Height=$(if($groupFocused){108}else{92})','$card.Button.Width=184','$card.Button.Width=142','$scroll.Height=188')){Need $n}
foreach($n in @("'xbox' {[void]`$names.Add('Xbox App.glb');[void]`$names.Add('Microsoft Xbox App.glb')}",'Resolve-HcShelfModelPath $Platform $Group')){Need $n}
if($text.Contains("'xbox' {[void]`$names.Add('Xbox.glb')")){throw 'Provider Xbox can still resolve to Original Xbox hardware GLB.'}
$view=$text.Substring($text.IndexOf('function New-Hc3DShelfLiveModelView'),$text.IndexOf('function Start-Hc3DShelfLoadTimer')-$text.IndexOf('function New-Hc3DShelfLiveModelView'));if(-not$view.Contains('New-Object HuymaierConsole.Modeling.LiveModelView -ArgumentList @($Path)')-or$view.Contains('@($Path,$true)')){throw 'V6 shelf is not using the full textured GLB constructor.'}
$res=$text.Substring($text.IndexOf('function Test-Hc3DCardShouldStayResident'),$text.IndexOf('function Set-Hc3DShelfViewFraming')-$text.IndexOf('function Test-Hc3DCardShouldStayResident'));foreach($n in @('Abs([int]$Card.ShelfIndex-$selected)-le1','return ([int]$Card.ShelfIndex-eq$selected)')){if(-not$res.Contains($n)){throw "Four-model residency contract missing: $n"}}
$near=$text.Substring($text.IndexOf('function Queue-Hc3DShelfNeighborhood'),$text.IndexOf('function Center-Hc3DShelfSelection')-$text.IndexOf('function Queue-Hc3DShelfNeighborhood'));foreach($n in @('@(0,1,-1)','@(0)')){if(-not$near.Contains($n)){throw "Dual-shelf lazy neighborhood contract missing: $n"}}
$spin=$text.Substring($text.IndexOf('function Start-Hc3DShelfSpinTimer'),$text.IndexOf('function Queue-Hc3DShelfNeighborhood')-$text.IndexOf('function Start-Hc3DShelfSpinTimer'));foreach($n in @('FromMilliseconds(50)','.Rotate(.34,0)','.Rotate(.12,0)',"@('Providers','Consoles')")){if(-not$spin.Contains($n)){throw "V6 turntable animation missing: $n"}};if($spin.Contains('Render-Page')){throw 'V6 turntable animation rebuilds Games.'}
$render=$text.Substring($text.IndexOf('function Render-Page'),$text.IndexOf('function Add-HcPlatformPresentationSettings')-$text.IndexOf('function Render-Page'));foreach($n in @('$script:Hc3DShelfMounted',"`$script:SelectedTab-eq1",'Deferred redundant Games 3D shelf rebuild','Reset-Hc3DShelfRuntime')){if(-not$render.Contains($n)){throw "Background refresh boundary missing: $n"}}
$expected=@('Arcade.glb','Atari 2600.glb','Atari Lynx.glb','Epic Games.glb','Neo Geo Pocket Color.glb','Neo Geo.glb','Nintendo 3DS.glb','Nintendo 64.glb','Nintendo DS.glb','Nintendo DSI.glb','Nintendo Entertainment System.glb','Nintendo Game Boy Advance.glb','Nintendo Game Boy Color.glb','Nintendo Game Boy.glb','Nintendo GameCube.glb','Nintendo Switch.glb','Nintendo Wii U.glb','Nintendo Wii.glb','PlayStation 2.glb','PlayStation 3.glb','Playstation 4.glb','Playstation 5.glb','Sega Dreamcast.glb','Sega Genesis.glb','Sega Logo.glb','Sega Master System.glb','Sega Mega Drive.glb','Sega Saturn.glb','Sony Playstation Portable.glb','Sony Playstation Vita.glb','Sony PlayStation.glb','Steam.glb','Super Nintendo Entertainment System.glb','XBOX 360.glb','Xbox One.glb','Xbox.glb');if($expected.Count-ne36){throw 'Original model filename contract changed.'};foreach($name in $expected){Need "'$name'"}
$loaderText=Get-Content -Raw $loader -Encoding UTF8;foreach($n in @('HUYMAIER_GLTF_MATERIAL_COMPAT_V2','KHR_texture_transform','KHR_materials_emissive_strength','KHR_materials_pbrSpecularGlossiness','KHR_materials_specular','KHR_materials_clearcoat','alphaMode','WrapCoordinate','ImageCache')){if(-not$loaderText.Contains($n)){throw "Full material pass missing: $n"}}
$controlText=Get-Content -Raw $control -Encoding UTF8;foreach($n in @('HUYMAIER_ROTATION_SAFE_MODEL_FRAMING_V2','MaterialCount','TextureCount','ImageCount','boundingDiameter')){if(-not$controlText.Contains($n)){throw "Rotation-safe control diagnostics missing: $n"}}
$opt=Get-Content -Raw $optimizer -Encoding UTF8;foreach($n in @('HUYMAIER_USER_3D_MODELS_RUNTIME_LOAD_V1','HuymaierUser3DModels.ps1','HUYMAIER_USER_3D_MODELS_PREFLIGHT_V1','HUYMAIER_USER_3D_MODELS_INSTALLER_CACHE_V1')){if(-not$opt.Contains($n)){throw "3D optimizer contract missing: $n"}}
$sources=@(Get-Content $sourceList -Encoding UTF8);if($sources-notcontains'HuymaierUser3DModels.ps1'){throw 'Release source list omits V6 presentation owner.'};if($sources-contains'Native/HuymaierBuiltInModelGenerator.cs'){throw 'Release source list includes retired generated GLB payload.'}
foreach($gate in @('platformModelDualShelfGate','platformModelProviderConsoleSplitGate','platformModelCompactRealEstateGate','platformModelProviderXboxContextGate','platformModelFullTextureConstructorGate','platformModelFourTextureResidencyGate','platformModelDualShelfTurntableGate','platformModelBackgroundRefreshSuppressionGate','platformModelMaterialCompatibilityGate','platformModelRotationSafeFramingGate','platformModelOriginalNamingGate','platformModelCustomizationOnlyGate','platformModelReservedHostVariableGate')){Write-Host ($gate+': success')}
