Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$worker=Join-Path $root 'Native\HuymaierModelPreviewWorker.cs';$aliases=Join-Path $root 'Native\HuymaierModelPreviewWpfAliases.cs';$control=Join-Path $root 'Native\HuymaierLiveModelControl.cs'
foreach($p in @($worker,$aliases,$control)){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "Live 3D render source missing: $p"}}
$workerText=Get-Content -Raw $worker -Encoding UTF8;$controlText=Get-Content -Raw $control -Encoding UTF8
foreach($n in @('HUYMAIER_GLTF_MATERIAL_COMPAT_V2','KHR_texture_transform','KHR_materials_emissive_strength','alphaMode','WrapMode','ImageCache')){if(-not$workerText.Contains($n)){throw "V6 material renderer missing: $n"}}
if(-not$controlText.Contains('HUYMAIER_ROTATION_SAFE_MODEL_FRAMING_V2')){throw 'V6 rotation-safe framing marker is missing.'}
Add-Type -AssemblyName PresentationFramework,PresentationCore,WindowsBase,System.Xaml,System.Web.Extensions
$csc=Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe';if(-not(Test-Path -LiteralPath $csc)){throw 'Framework64 csc.exe was not found.'}
$temp=Join-Path $(if($env:RUNNER_TEMP){$env:RUNNER_TEMP}else{[IO.Path]::GetTempPath()}) ('hc-v6-texture-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Force -Path $temp|Out-Null
function New-CheckerPng{$w=8;$h=8;$stride=$w*4;$pixels=New-Object byte[] ($stride*$h);for($y=0;$y-lt$h;$y++){for($x=0;$x-lt$w;$x++){$o=$y*$stride+$x*4;if($x-lt4){$pixels[$o]=24;$pixels[$o+1]=32;$pixels[$o+2]=238}else{$pixels[$o]=238;$pixels[$o+1]=48;$pixels[$o+2]=30};$pixels[$o+3]=255}};$bmp=[Windows.Media.Imaging.BitmapSource]::Create($w,$h,96,96,[Windows.Media.PixelFormats]::Bgra32,$null,$pixels,$stride);$enc=New-Object Windows.Media.Imaging.PngBitmapEncoder;$enc.Frames.Add([Windows.Media.Imaging.BitmapFrame]::Create($bmp));$ms=New-Object IO.MemoryStream;try{$enc.Save($ms);return ,([byte[]]$ms.ToArray())}finally{$ms.Dispose()}}
function New-V6ProbeGlb([string]$Path){$png=New-CheckerPng;$ms=New-Object IO.MemoryStream;$bw=New-Object IO.BinaryWriter($ms);try{foreach($f in @([single]-1,[single]-.72,[single]0,[single]1,[single]-.72,[single]0,[single]1,[single].72,[single]0,[single]-1,[single].72,[single]0)){$bw.Write($f)};foreach($i in 0..3){$bw.Write([single]0);$bw.Write([single]0);$bw.Write([single]1)};foreach($f in @([single]0,[single]0,[single]1,[single]0,[single]1,[single]1,[single]0,[single]1)){$bw.Write($f)};foreach($ix in @([uint16]0,[uint16]1,[uint16]2,[uint16]0,[uint16]2,[uint16]3)){$bw.Write($ix)};$img=[int]$ms.Position;$bw.Write($png);while(($ms.Position%4)-ne0){$bw.Write([byte]0)};$bw.Flush();$bin=[byte[]]$ms.ToArray()}finally{$bw.Dispose();$ms.Dispose()}
$json="{`"asset`":{`"version`":`"2.0`"},`"extensionsUsed`":[`"KHR_texture_transform`",`"KHR_materials_emissive_strength`"],`"scene`":0,`"scenes`":[{`"nodes`":[0]}],`"nodes`":[{`"mesh`":0}],`"meshes`":[{`"primitives`":[{`"attributes`":{`"POSITION`":0,`"NORMAL`":1,`"TEXCOORD_0`":2},`"indices`":3,`"material`":0,`"mode`":4}]}],`"materials`":[{`"doubleSided`":true,`"alphaMode`":`"BLEND`",`"pbrMetallicRoughness`":{`"baseColorFactor`":[1,1,1,.92],`"baseColorTexture`":{`"index`":0,`"texCoord`":0,`"extensions`":{`"KHR_texture_transform`":{`"offset`":[.08,.03],`"scale`":[.84,.92],`"rotation`":.12}}},`"metallicFactor`":0,`"roughnessFactor`":.85},`"emissiveTexture`":{`"index`":0,`"texCoord`":0},`"emissiveFactor`":[.18,.18,.18],`"extensions`":{`"KHR_materials_emissive_strength`":{`"emissiveStrength`":1.5}}}],`"samplers`":[{`"wrapS`":33071,`"wrapT`":33648}],`"textures`":[{`"sampler`":0,`"source`":0}],`"images`":[{`"bufferView`":4,`"mimeType`":`"image/png`"}],`"buffers`":[{`"byteLength`":$($bin.Length)}],`"bufferViews`":[{`"buffer`":0,`"byteOffset`":0,`"byteLength`":48},{`"buffer`":0,`"byteOffset`":48,`"byteLength`":48},{`"buffer`":0,`"byteOffset`":96,`"byteLength`":32},{`"buffer`":0,`"byteOffset`":128,`"byteLength`":12},{`"buffer`":0,`"byteOffset`":$img,`"byteLength`":$($png.Length)}],`"accessors`":[{`"bufferView`":0,`"componentType`":5126,`"count`":4,`"type`":`"VEC3`",`"min`":[-1,-.72,0],`"max`":[1,.72,0]},{`"bufferView`":1,`"componentType`":5126,`"count`":4,`"type`":`"VEC3`"},{`"bufferView`":2,`"componentType`":5126,`"count`":4,`"type`":`"VEC2`"},{`"bufferView`":3,`"componentType`":5123,`"count`":6,`"type`":`"SCALAR`",`"min`":[0],`"max`":[3]}]}";$jb=[Text.Encoding]::UTF8.GetBytes($json);$pad=(4-($jb.Length%4))%4;$jc=New-Object byte[] ($jb.Length+$pad);[Array]::Copy($jb,$jc,$jb.Length);for($i=$jb.Length;$i-lt$jc.Length;$i++){$jc[$i]=0x20};$total=12+8+$jc.Length+8+$bin.Length;$fs=[IO.File]::Create($Path);$out=New-Object IO.BinaryWriter($fs);try{$out.Write([byte[]](0x67,0x6C,0x54,0x46));$out.Write([uint32]2);$out.Write([uint32]$total);$out.Write([uint32]$jc.Length);$out.Write([uint32]0x4E4F534A);$out.Write($jc);$out.Write([uint32]$bin.Length);$out.Write([uint32]0x004E4942);$out.Write($bin)}finally{$out.Dispose();$fs.Dispose()}}
function Get-RenderStats($View,[string]$Label){$w=260;$h=150;$View.Width=$w;$View.Height=$h;$View.Measure((New-Object Windows.Size($w,$h)));$View.Arrange((New-Object Windows.Rect(0,0,$w,$h)));$View.UpdateLayout();$bmp=New-Object Windows.Media.Imaging.RenderTargetBitmap($w,$h,96,96,[Windows.Media.PixelFormats]::Pbgra32);$bmp.Render($View);$stride=$w*4;$pixels=New-Object byte[] ($stride*$h);$bmp.CopyPixels($pixels,$stride,0);$visible=0;$red=0;$blue=0;$edge=0;for($y=0;$y-lt$h;$y++){for($x=0;$x-lt$w;$x++){$o=$y*$stride+$x*4;$b=[int]$pixels[$o];$g=[int]$pixels[$o+1];$r=[int]$pixels[$o+2];$a=[int]$pixels[$o+3];if($a-le12){continue};$visible++;if($r-gt$b+20-and$r-gt$g+15){$red++};if($b-gt$r+20-and$b-gt$g+15){$blue++};if($x-lt2-or$y-lt2-or$x-ge$w-2-or$y-ge$h-2){$edge++}}};if($visible-lt400){throw "$Label rendered only $visible pixels."};if($red-lt25-or$blue-lt25){throw "$Label lost the transformed embedded texture (red=$red blue=$blue visible=$visible)."};Write-Host "$Label visiblePixels=$visible redPixels=$red bluePixels=$blue edgePixels=$edge";[pscustomobject]@{Visible=$visible;Red=$red;Blue=$blue;Edge=$edge}}
try{$refs=@([Uri].Assembly.Location,[Linq.Enumerable].Assembly.Location,[Web.Script.Serialization.JavaScriptSerializer].Assembly.Location,[Windows.DependencyObject].Assembly.Location,[Windows.Media.Visual].Assembly.Location,[Windows.Window].Assembly.Location,[System.Xaml.XamlReader].Assembly.Location)|Select-Object -Unique;$dll=Join-Path $temp 'HuymaierLiveModel3D.dll';$args=@('/noconfig','/nologo','/target:library','/platform:x64','/optimize+',('/out:'+$dll));foreach($r in $refs){$args+=('/reference:'+$r)};$args+=@($worker,$aliases,$control);& $csc @args;if($LASTEXITCODE-ne0-or-not(Test-Path $dll)){throw 'V6 visual-probe DLL compilation failed.'};Add-Type -Path $dll;$glb=Join-Path $temp 'v6-material.glb';New-V6ProbeGlb $glb;$view=New-Object HuymaierConsole.Modeling.LiveModelView -ArgumentList @($glb);if([bool]$view.CardMode){throw 'V6 shelf entered geometry-only mode.'};if([int]$view.GeometryCount-ne1-or[int]$view.VertexCount-ne4){throw 'V6 probe geometry counts are wrong.'};if([int]$view.MaterialCount-lt1-or[int]$view.TextureCount-lt1-or[int]$view.ImageCount-lt1){throw 'V6 GLB diagnostics did not detect material/texture/image data.'};$view.SetScalePercent(70);$before=Get-RenderStats $view 'v6TexturedShelf';if([int]$before.Edge-ne0){throw "V6 shelf framing touched the edge before rotation ($($before.Edge))."};$yaw=[double]$view.Yaw;$view.Rotate(45,0);$after=Get-RenderStats $view 'v6TexturedShelfRotated';if([math]::Abs([double]$view.Yaw-$yaw)-lt30){throw 'V6 shelf did not rotate.'};if([int]$after.Edge-ne0){throw "V6 shelf framing clipped/touched the edge after rotation ($($after.Edge))."};foreach($gate in @('platformModelV6TexturePixelGate','platformModelTextureTransformGate','platformModelSamplerGate','platformModelAlphaBlendGate','platformModelEmissiveTextureGate','platformModelTextureDiagnosticsGate','platformModelTurntableRotationPixelGate','platformModelSafeRotationFramingPixelGate')){Write-Host ($gate+': success')}}finally{Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue}
