Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$baseModule=Join-Path $root 'HuymaierPlatformModels.ps1'
$liveModule=Join-Path $root 'HuymaierLivePlatformModels.ps1'
$userModule=Join-Path $root 'HuymaierUser3DModels.ps1'
$modelLoader=Join-Path $root 'Native\HuymaierModelPreviewWorker.cs'
$modelAliases=Join-Path $root 'Native\HuymaierModelPreviewWpfAliases.cs'
$liveControl=Join-Path $root 'Native\HuymaierLiveModelControl.cs'
$optimizer=Join-Path $root '.build\Optimize-Platform3DModels.ps1'
$pruneOptimizer=Join-Path $root '.build\Optimize-Retired3DPayloadPrune.ps1'
$modelMap=Join-Path $root 'Assets\Models\model-map.json'
foreach($p in @($baseModule,$liveModule,$userModule,$modelLoader,$modelAliases,$liveControl,$optimizer,$pruneOptimizer,$modelMap)){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "Platform-model source is missing: $p"}}
foreach($ps in @($baseModule,$liveModule,$userModule,$optimizer,$pruneOptimizer)){$tokens=$null;$errors=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($ps,[ref]$tokens,[ref]$errors);if(@($errors).Count){throw "$ps failed Windows PowerShell 5.1 parse: $(@($errors|ForEach-Object{$_.Message}) -join '; ')"};if($ps -in @($baseModule,$liveModule,$userModule)){foreach($v in @($ast.FindAll({param($n)$n -is [Management.Automation.Language.VariableExpressionAst]},$true))){if([string]::Equals([string]$v.VariablePath.UserPath,'Host',[StringComparison]::OrdinalIgnoreCase)){throw "Active platform presentation runtime references reserved `$Host: $ps line $($v.Extent.StartLineNumber)"}}}}
$baseText=Get-Content -Raw $baseModule -Encoding UTF8;foreach($n in @('HUYMAIER_PLATFORM_PRESENTATION_BASE_V2','HcModelsBaseNewPlatformCard','HcModelsBaseAddPlatformRail','Initialize-HcPlatformModelConfig','PlatformIconScale','PlatformModelScale')){if(-not$baseText.Contains($n)){throw "Platform base contract missing: $n"}};foreach($bad in @('HuymaierModelPreviewWorker.exe','Request-HcModelPreview','function New-PlatformCard','function Add-PlatformRail')){if($baseText.Contains($bad)){throw "Platform base still owns retired rendering: $bad"}}
$liveText=Get-Content -Raw $liveModule -Encoding UTF8;foreach($n in @('HUYMAIER_LIVE_PLATFORM_3D_HELPERS_V3','HUYMAIER_CONTEXT_AWARE_MODEL_VIEWER_V1','HuymaierLiveModel3D.dll','Initialize-HcLiveModelAssembly','New-HcLiveModelView','Open-HcPlatformModelViewer','Close-HcPlatformModelViewer','function Invoke-SecondaryAction','function Apply-ControllerNavigation')){if(-not$liveText.Contains($n)){throw "Live helper V3 contract missing: $n"}};foreach($bad in @('function New-PlatformCard','function Add-PlatformRail','Set-HcAtlasFallbackVisual','HuymaierPlatformAtlas')){if($liveText.Contains($bad)){throw "Live helper still owns retired presentation: $bad"}}
$userText=Get-Content -Raw $userModule -Encoding UTF8;foreach($n in @('HUYMAIER_USER_3D_MODELS_RUNTIME_V6','HUYMAIER_3D_DUAL_SHELF_RUNTIME_V1','HUYMAIER_3D_TEXTURED_BOUNDED_RESIDENCY_V2','Providers','Consoles','Test-HcStorefrontPlatform','maxTextureResidency=4')){if(-not$userText.Contains($n)){throw "V6 presentation owner contract missing: $n"}}
$loaderText=Get-Content -Raw $modelLoader -Encoding UTF8;foreach($n in @('HUYMAIER_GLTF_MATERIAL_COMPAT_V2','KHR_texture_transform','KHR_materials_emissive_strength','KHR_materials_pbrSpecularGlossiness','KHR_materials_specular','KHR_materials_clearcoat','alphaMode','sampler','ImageCache')){if(-not$loaderText.Contains($n)){throw "GLB material compatibility contract missing: $n"}}
$controlText=Get-Content -Raw $liveControl -Encoding UTF8;foreach($n in @('HUYMAIER_ROTATION_SAFE_MODEL_FRAMING_V2','public sealed class LiveModelView','Viewport3D','SetScalePercent','Rotate(double yawDelta','MaterialCount','TextureCount','ImageCount','boundingDiameter')){if(-not$controlText.Contains($n)){throw "Live control V6 contract missing: $n"}}
$map=Get-Content -Raw $modelMap -Encoding UTF8|ConvertFrom-Json;if([int]$map.schemaVersion-ne2){throw '3D model map schema version must remain 2.'};if($null-eq$map.sourceModels){throw '3D model map no longer contains original source-model provenance.'}
Add-Type -AssemblyName PresentationFramework,PresentationCore,WindowsBase,System.Xaml,System.Web.Extensions
$csc=Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe';if(-not(Test-Path $csc)){throw 'Framework64 csc.exe was not found.'}
$tempRoot=$(if($env:RUNNER_TEMP){$env:RUNNER_TEMP}else{[IO.Path]::GetTempPath()});$temp=Join-Path $tempRoot ('hc-platform-v6-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Force -Path $temp|Out-Null
try{$refs=@([Uri].Assembly.Location,[Linq.Enumerable].Assembly.Location,[Web.Script.Serialization.JavaScriptSerializer].Assembly.Location,[Windows.DependencyObject].Assembly.Location,[Windows.Media.Visual].Assembly.Location,[Windows.Window].Assembly.Location,[System.Xaml.XamlReader].Assembly.Location)|Select-Object -Unique;$dll=Join-Path $temp 'HuymaierLiveModel3D.dll';$args=@('/noconfig','/nologo','/target:library','/platform:x64','/optimize+',('/out:'+$dll));foreach($r in $refs){$args+=('/reference:'+$r)};$args+=@($modelLoader,$modelAliases,$liveControl);& $csc @args;if($LASTEXITCODE-ne0-or-not(Test-Path $dll)){throw 'V6 live platform-model x64 DLL compile failed.'};$bytes=[IO.File]::ReadAllBytes($dll);$pe=[BitConverter]::ToInt32($bytes,0x3C);$machine=[BitConverter]::ToUInt16($bytes,$pe+4);if($machine-ne0x8664){throw 'HuymaierLiveModel3D.dll is not x64.'}
$core=Join-Path $temp 'HuymaierConsole.ps1';$bootstrap=Join-Path $temp 'HuymaierBootstrap.ps1';$installer=Join-Path $temp 'Install-HuymaierConsole.ps1';$builder=Join-Path $temp 'Build-HuymaierReleaseCandidate.Core.ps1';Copy-Item (Join-Path $root 'HuymaierConsole.ps1') $core;Copy-Item (Join-Path $root 'HuymaierBootstrap.ps1') $bootstrap;Copy-Item (Join-Path $root 'Install-HuymaierConsole.ps1') $installer;Copy-Item (Join-Path $root '.build\Build-HuymaierReleaseCandidate.Core.ps1') $builder;& $optimizer -CorePath $core -BootstrapPath $bootstrap -InstallerScriptPath $installer -CoreBuilderPath $builder;& $pruneOptimizer -CoreBuilderPath $builder;foreach($ps in @($core,$bootstrap,$installer,$builder)){$t=$null;$e=$null;[void][Management.Automation.Language.Parser]::ParseFile($ps,[ref]$t,[ref]$e);if(@($e).Count){throw "Transformed platform-model file failed parse: $ps :: $(@($e|ForEach-Object{$_.Message}) -join '; ')"}};$coreText=Get-Content -Raw $core;$bootstrapText=Get-Content -Raw $bootstrap;$installerText=Get-Content -Raw $installer;$builderText=Get-Content -Raw $builder;foreach($n in @('HUYMAIER_PLATFORM_3D_MODELS_RUNTIME_V2','HUYMAIER_USER_3D_MODELS_RUNTIME_LOAD_V1','HuymaierUser3DModels.ps1','HuymaierLivePlatformModels.ps1')){if(-not$coreText.Contains($n)){throw "Transformed core contract missing: $n"}};if($bootstrapText.Contains('HuymaierPlatformAtlas.ps1')-or$installerText.Contains('HuymaierPlatformAtlas.ps1')){throw 'Retired atlas runtime survived bootstrap/installer transform.'};foreach($n in @('HuymaierLiveModel3D.dll','HUYMAIER_RETIRED_3D_PAYLOAD_PRUNE_V1','HuymaierModelPreviewWorker.exe','Assets\Models\Live')){if(-not$builderText.Contains($n)){throw "Staged builder/prune contract missing: $n"}}}finally{Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}
foreach($gate in @('platformModelV6OwnerGate','platformModelDualShelfGate','platformModelMaterialCompatibilityGate','platformModelRotationSafeFramingGate','platformModelLiveDllX64Gate','platformModelRetiredPayloadPruneGate','platformModelReservedHostVariableGate')){Write-Host ($gate+': success')}
