param()
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
# HUYMAIER_V0308_COVER_ART_TRANSFORM_V2
$root=Split-Path -Parent $PSScriptRoot
function Read-NormalizedText([string]$Path){return ([IO.File]::ReadAllText($Path,[Text.Encoding]::UTF8).Replace("`r`n","`n"))}
function Write-NormalizedText([string]$Path,[string]$Text){$out=$Text.Replace("`n","`r`n");[IO.File]::WriteAllText($Path,$out,(New-Object Text.UTF8Encoding($true)))}
function Replace-Required([string]$Text,[string]$Old,[string]$New,[string]$Label){if(-not $Text.Contains($Old)){throw "v0.30.8 transform anchor missing: $Label"};return $Text.Replace($Old,$New)}
$lf="`n"
$corePath=Join-Path $root 'HuymaierConsole.ps1';$core=Read-NormalizedText $corePath
if($core -notmatch 'HUYMAIER_V0308_COVER_ART_CORE_V1'){
$core=Replace-Required $core '$script:AppVersion = ''0.30.7''' '$script:AppVersion = ''0.30.8''' 'core version'
$anchor='$script:ArtworkWorkerPath = Join-Path $script:BaseDir ''HuymaierArtworkWorker.ps1''';$core=Replace-Required $core $anchor (@($anchor,'$script:ArtworkManagementModulePath = Join-Path $script:BaseDir ''HuymaierArtworkManagement.ps1'' # HUYMAIER_V0308_COVER_ART_CORE_V1') -join $lf) 'management module path'
$core=Replace-Required $core '        SteamGridDbApiKey = ''''' (@('        SteamGridDbApiKey = ''''','        TheGamesDbApiKey = ''''') -join $lf) 'TGDB config default'
$core=Replace-Required $core '''OnlineArtworkEnabled'',''SteamGridDbApiKey'',''PlatformBackgroundsEnabled''' '''OnlineArtworkEnabled'',''SteamGridDbApiKey'',''TheGamesDbApiKey'',''PlatformBackgroundsEnabled''' 'TGDB config allowlist'
$core=Replace-Required $core '    param([switch]$ResetCursor,[switch]$Force,[string]$Platform='''')' '    param([switch]$ResetCursor,[switch]$Force,[string]$Platform='''',[string]$GameId='''',[string]$GameName='''')' 'scan parameters'
$anchor='        $platformArg=if($Platform){'' -Platform "''+($Platform -replace ''"'','''')+''"''}else{''''}';$core=Replace-Required $core $anchor (@($anchor,'        $gameIdArg=if($GameId){'' -GameId "''+($GameId -replace ''"'','''')+''"''}else{''''}','        $gameNameArg=if($GameName){'' -GameName "''+($GameName -replace ''"'','''')+''"''}else{''''}') -join $lf) 'single game args'
$core=Replace-Required $core '$script:ArtworkResultPath+''"''+$platformArg' '$script:ArtworkResultPath+''"''+$platformArg+$gameIdArg+$gameNameArg' 'worker command args'
$anchor='        ''steamgriddb-key'' { Show-NativeKeyboard -Title ''SteamGridDB artwork key'' -InitialText ([string]$script:Config.SteamGridDbApiKey) -Mode ''SteamGridDbApiKey'' -Context $null }';$core=Replace-Required $core $anchor (@($anchor,'        ''thegamesdb-key'' { Show-NativeKeyboard -Title ''TheGamesDB API key'' -InitialText ([string]$script:Config.TheGamesDbApiKey) -Mode ''TheGamesDbApiKey'' -Context $null }','        ''artwork-retry-unresolved'' { if(Get-Command Start-HcArtworkRetryUnresolved -ErrorAction SilentlyContinue){Start-HcArtworkRetryUnresolved};Render-Page }','        ''artwork-refresh-platform'' { if(Get-Command Start-HcArtworkPlatformRefresh -ErrorAction SilentlyContinue){Start-HcArtworkPlatformRefresh};Render-Page }','        ''artwork-open-cache'' { if(Get-Command Open-HcArtworkCache -ErrorAction SilentlyContinue){Open-HcArtworkCache} }') -join $lf) 'artwork handlers'
$anchor='                $sgdbState=if([string]::IsNullOrWhiteSpace([string]$script:Config.SteamGridDbApiKey)){''NOT CONFIGURED''}else{''CONFIGURED''}';$core=Replace-Required $core $anchor (@($anchor,'                $tgdbState=if([string]::IsNullOrWhiteSpace([string]$script:Config.TheGamesDbApiKey)){''NOT CONFIGURED''}else{''CONFIGURED''}') -join $lf) 'settings state'
$core=Replace-Required $core '                    HeroText="SteamGridDB: $sgdbState`nSteam games use their Steam AppID; other Windows storefronts use normalized title matching.`nLocal storefront/emulator artwork remains preferred before online fallbacks."' '                    HeroText="TheGamesDB: $tgdbState  |  SteamGridDB: $sgdbState`nProvider/local artwork is preserved first. Missing covers then use platform-aware cached and online matching.`nLow-confidence matches are skipped and unresolved lookups are back-off cached."' 'settings hero'
$anchor='                        (New-Action ''steamgriddb-key'' $(if([string]::IsNullOrWhiteSpace([string]$script:Config.SteamGridDbApiKey)){''SteamGridDB API key: Add personal key''}else{''SteamGridDB API key: Configured''}) ''Opens the Huymaier native keyboard. Your personal key is stored locally in Huymaier Console config and is used only for SteamGridDB API requests.''),';$core=Replace-Required $core $anchor (@('                        (New-Action ''thegamesdb-key'' $(if([string]::IsNullOrWhiteSpace([string]$script:Config.TheGamesDbApiKey)){''TheGamesDB API key: Add personal key''}else{''TheGamesDB API key: Configured''}) ''Primary automated missing-cover source. The key is stored locally and used only for TheGamesDB API requests.''),',$anchor) -join $lf) 'TGDB action'
$core=Replace-Required $core '                        (New-Action ''online-artwork-toggle'' $(if($script:Config.OnlineArtworkEnabled){''Online box art: On''}else{''Online box art: Off''}) ''Steam local/CDN and provider artwork are tried first; SteamGridDB is an optional cross-storefront fallback.''),' '                        (New-Action ''online-artwork-toggle'' $(if($script:Config.OnlineArtworkEnabled){''Online box art: On''}else{''Online box art: Off''}) ''Provider/local artwork is preserved first; TheGamesDB is the primary platform-aware external source and SteamGridDB remains a PC fallback.''),' 'source order text'
$anchor='                        (New-Action ''artwork-refresh'' ''Refresh missing box art'' ''Rescans entries that still do not have usable artwork.''),';$core=Replace-Required $core $anchor (@($anchor,'                        (New-Action ''artwork-retry-unresolved'' ''Retry unresolved cover art'' ''Clears failed-lookup backoff and retries missing covers.''),','                        (New-Action ''artwork-refresh-platform'' ''Refresh current platform cover art'' ''Runs the missing-art matcher only for the currently selected game platform.''),','                        (New-Action ''artwork-open-cache'' ''Open artwork cache & mappings'' ''Opens cached images, provenance data, failed lookups, and the optional The Cover Project mapping file.''),') -join $lf) 'maintenance actions'
$anchor='if (Test-Path -LiteralPath $script:GameExperienceModulePath) {';$core=Replace-Required $core $anchor (@('if (Test-Path -LiteralPath $script:ArtworkManagementModulePath) {','    try { . $script:ArtworkManagementModulePath }','    catch { Write-Log "Artwork management module load failed: $($_.Exception.Message)" ''ERROR'' }','}',$anchor) -join $lf) 'management module load'
Write-NormalizedText $corePath $core}
$workerPath=Join-Path $root 'HuymaierArtworkWorker.ps1';$worker=Read-NormalizedText $workerPath
if($worker -notmatch 'HUYMAIER_V0308_COVER_ART_WORKER_V1'){
$worker=Replace-Required $worker '    [string]$Platform=''''' (@('    [string]$Platform='''',','    [string]$GameId='''',','    [string]$GameName=''''') -join $lf) 'worker parameters'
$anchor='    $config=Get-Content -Raw -LiteralPath $ConfigPath|ConvertFrom-Json';$worker=Replace-Required $worker $anchor (@($anchor,'    # HUYMAIER_V0308_COVER_ART_WORKER_V1','    $externalSourcesPath=Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) ''HuymaierArtworkSources.ps1''','    if(Test-Path -LiteralPath $externalSourcesPath -PathType Leaf){. $externalSourcesPath}') -join $lf) 'source module load'
$worker=Replace-Required $worker '        if(-not $found){$found=Get-IndexedArt $game}' '' 'move index';$worker=Replace-Required $worker '        if(-not $found){$found=Try-EsDeMediaArt $game}' '' 'move ESDE'
$anchor='        if(-not $id){$id=([string](Get-Prop $game ''Source'' ''Game''))+'':''+(Normalize-Name ([string](Get-Prop $game ''Name'' '''')))}';$worker=Replace-Required $worker $anchor (@($anchor,'        if($GameId -or $GameName){','            $entryName=[string](Get-Prop $game ''Name'' '''')','            $actualId=$id.ToLowerInvariant();$requestedId=$GameId.ToLowerInvariant()','            $idMatch=(-not $GameId -or $actualId -eq $requestedId -or $actualId.EndsWith('':''+$requestedId) -or $requestedId.EndsWith('':''+$actualId))','            $nameMatch=(-not $GameName -or (Normalize-Name $entryName) -eq (Normalize-Name $GameName))','            if(-not ($idMatch -and $nameMatch)){continue}','        }') -join $lf) 'single game filter'
$worker=Replace-Required $worker '    foreach($key in @((Get-ArtIndexKey $source $name),(Get-ArtIndexKey ''*'' $name))){if($key -and $artIndex.ContainsKey($key)){if(Test-ImageFile ([string]$artIndex[$key])){return [string]$artIndex[$key]}}}' '    $keys=New-Object System.Collections.ArrayList;[void]$keys.Add((Get-ArtIndexKey $source $name));if(-not ((Get-Command Test-HcPlatformSpecificArtworkSource -ErrorAction SilentlyContinue) -and (Test-HcPlatformSpecificArtworkSource $source))){[void]$keys.Add((Get-ArtIndexKey ''*'' $name))};foreach($key in @($keys)){if($key -and $artIndex.ContainsKey($key)){if(Test-ImageFile ([string]$artIndex[$key])){return [string]$artIndex[$key]}}}' 'safe index lookup'
$worker=Replace-Required $worker '    $artIndex[(Get-ArtIndexKey $Source $Name)]=$Path;$artIndex[(Get-ArtIndexKey ''*'' $Name)]=$Path' '    $artIndex[(Get-ArtIndexKey $Source $Name)]=$Path;if(-not ((Get-Command Test-HcPlatformSpecificArtworkSource -ErrorAction SilentlyContinue) -and (Test-HcPlatformSpecificArtworkSource $Source))){$artIndex[(Get-ArtIndexKey ''*'' $Name)]=$Path}' 'safe index save'
$anchor='        if(-not $found){$found=Try-LibretroArt $game $target}';$worker=Replace-Required $worker $anchor (@('        if(-not $found){$found=Get-IndexedArt $game}','        if(-not $found){$found=Try-EsDeMediaArt $game}','        $externalArt=$null','        if(-not $found -and (Get-Command Try-HcTheGamesDbArt -ErrorAction SilentlyContinue)){$externalArt=Try-HcTheGamesDbArt $game $target;if($null -ne $externalArt){$found=[string]$externalArt.Path}}','        if(-not $found -and (Get-Command Try-HcCoverProjectMappingArt -ErrorAction SilentlyContinue)){$externalArt=Try-HcCoverProjectMappingArt $game $target;if($null -ne $externalArt){$found=[string]$externalArt.Path}}',$anchor) -join $lf) 'external priority'
$worker=Replace-Required $worker '        if(-not $found){$found=Try-WikipediaArt $game $target}' '' 'disable Wikipedia';$worker=Replace-Required $worker '        if(-not $found){$found=Try-BingImageArt $game $target}' '' 'disable Bing'
$worker=Replace-Required $worker '    $hasMore=($index -lt $games.Count)' '    $hasMore=(-not ($GameId -or $GameName) -and ($index -lt $games.Count))' 'single game continuation'
$anchor=@('    Save-ArtIndex','    Write-AtomicJson $ResultPath $result') -join $lf;$worker=Replace-Required $worker $anchor (@('    Save-ArtIndex','    if(Get-Command Save-HcArtworkAuxiliaryState -ErrorAction SilentlyContinue){Save-HcArtworkAuxiliaryState}','    Write-AtomicJson $ResultPath $result') -join $lf) 'aux cache save'
Write-NormalizedText $workerPath $worker}
$gamePath=Join-Path $root 'HuymaierGameExperience.ps1';$game=Read-NormalizedText $gamePath
if($game -notmatch 'HUYMAIER_V0308_GAME_ARTWORK_MENU_V1'){
$anchor='            [void]$entries.Add([pscustomobject]@{Id=''modal-settings-back'';Title=''Back'';Subtitle=''Return to game options.'';Enabled=$true})';$game=Replace-Required $game $anchor (@('            # HUYMAIER_V0308_GAME_ARTWORK_MENU_V1','            [void]$entries.Add([pscustomobject]@{Id=''game-art-search'';Title=''Search cover art'';Subtitle=''Search this title using the platform-aware missing-cover pipeline.'';Enabled=$true})','            if((Get-Command Test-HcSelectedGameHasExternalArtwork -ErrorAction SilentlyContinue) -and (Test-HcSelectedGameHasExternalArtwork)){[void]$entries.Add([pscustomobject]@{Id=''game-art-revert'';Title=''Revert to provider / default'';Subtitle=''Unlink the externally cached cover and return to provider/default artwork.'';Enabled=$true})}','            [void]$entries.Add([pscustomobject]@{Id=''game-art-cache'';Title=''Open artwork cache'';Subtitle=''Open cached artwork, provenance, failures, and manual mappings.'';Enabled=$true})',$anchor) -join $lf) 'game artwork menu'
$anchor='        ''game-browse-files'' {Close-HcGameModal;$path=[string](Get-EntryProperty (Get-HcSelectedGame) ''InstallPath'' (Get-EntryProperty (Get-HcSelectedGame) ''Path'' ''''));if($path){Start-UriOrShellTarget $path}}';$game=Replace-Required $game $anchor (@('        ''game-art-search'' {Close-HcGameModal;if(Get-Command Start-HcSelectedGameArtworkRefresh -ErrorAction SilentlyContinue){Start-HcSelectedGameArtworkRefresh}}','        ''game-art-revert'' {Close-HcGameModal;if(Get-Command Reset-HcSelectedGameArtwork -ErrorAction SilentlyContinue){Reset-HcSelectedGameArtwork}}','        ''game-art-cache'' {Close-HcGameModal;if(Get-Command Open-HcArtworkCache -ErrorAction SilentlyContinue){Open-HcArtworkCache}}',$anchor) -join $lf) 'game artwork actions';Write-NormalizedText $gamePath $game}
$bootstrapPath=Join-Path $root 'HuymaierBootstrap.ps1';$bootstrap=Read-NormalizedText $bootstrapPath
if($bootstrap -notmatch 'HUYMAIER_V0308_ARTWORK_PREFLIGHT_V1'){
$bootstrap=Replace-Required $bootstrap '$script:ExpectedConsoleVersion=''0.30.7''' '$script:ExpectedConsoleVersion=''0.30.8''' 'bootstrap version';$anchor='$artworkWorkerPath=Join-Path $baseDir ''HuymaierArtworkWorker.ps1''';$bootstrap=Replace-Required $bootstrap $anchor (@($anchor,'$artworkSourcesPath=Join-Path $baseDir ''HuymaierArtworkSources.ps1'' # HUYMAIER_V0308_ARTWORK_PREFLIGHT_V1','$artworkManagementPath=Join-Path $baseDir ''HuymaierArtworkManagement.ps1''') -join $lf) 'bootstrap module paths';$anchor='        [pscustomobject]@{Path=$artworkWorkerPath;Label=''Online artwork worker''},';$bootstrap=Replace-Required $bootstrap $anchor (@($anchor,'        [pscustomobject]@{Path=$artworkSourcesPath;Label=''TheGamesDB and curated artwork sources''},','        [pscustomobject]@{Path=$artworkManagementPath;Label=''Artwork management UI helpers''},') -join $lf) 'bootstrap preflight';Write-NormalizedText $bootstrapPath $bootstrap}
$appxPath=Join-Path $root 'FSEPackage\AppxManifest.xml';$appx=Read-NormalizedText $appxPath;if($appx.Contains('Version="0.30.7.0"')){$appx=Replace-Required $appx 'Version="0.30.7.0"' 'Version="0.30.8.0"' 'AppX version'}elseif(-not $appx.Contains('Version="0.30.8.0"')){throw 'AppX version anchor missing'};Write-NormalizedText $appxPath $appx
$manifestPath=Join-Path $root 'manifest.json';$manifest=Get-Content -Raw -LiteralPath $manifestPath -Encoding UTF8|ConvertFrom-Json;$manifest.version='0.30.8';$manifest.baseVersion='0.30.7';$manifest.build='cover-art-fallback-rc1';$manifest.builtFrom='HC0307.zip';$features=New-Object System.Collections.ArrayList;foreach($feature in @($manifest.features)){[void]$features.Add($feature)};foreach($feature in @('adds TheGamesDB as the primary platform-aware automated missing-cover source with front-box-art preference, conservative confidence gates and API-key support','persists external artwork provenance, matched title/platform/source URL/cache path/confidence and negative lookup backoff so restarts and library refreshes do not repeatedly hammer external services','adds a curated The Cover Project mapping path without fragile automatic scraping, plus per-game Search cover art, Revert to provider/default and Open artwork cache controls','makes cached artwork keys platform-safe for console libraries and disables unstructured Wikipedia/Bing auto-assignment to reduce incorrect covers','keeps artwork matching in the existing background worker and preserves the v0.30.7 console-only studio lighting plus the untouched provider/storefront 3D model path')){if(-(@($features) -contains $feature)){[void]$features.Add($feature)}};$manifest.features=[object[]]$features.ToArray();$manifest.description='v0.30.8 adds a safe platform-aware missing-cover pipeline led by TheGamesDB, durable cache/provenance/failure state, curated The Cover Project mappings, and per-game artwork maintenance while preserving v0.30.7 console lighting and provider-model isolation.';$manifest|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $manifestPath -Encoding UTF8
Write-Host 'Applied Huymaier Console v0.30.8 cover-art fallback transform.'
