param(
 [Parameter(Mandatory=$true)][string]$StageRoot,
 [Parameter(Mandatory=$true)][string]$ValidationPath
)
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
function NeedFile([string]$rel){$p=Join-Path $StageRoot $rel;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "Staged V6 payload missing: $rel"};$p}
function NeedText([string]$rel,[string[]]$needles){$raw=Get-Content -Raw -LiteralPath (NeedFile $rel) -Encoding UTF8;foreach($n in $needles){if($raw.IndexOf($n,[StringComparison]::Ordinal)-lt0){throw "$rel missing staged V6 contract: $n"}};$raw}
function CheckPs([string]$rel){$p=NeedFile $rel;$t=$null;$e=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($p,[ref]$t,[ref]$e);if(@($e).Count){throw "$rel failed PowerShell 5.1 parse: $(@($e|ForEach-Object{$_.Message}) -join '; ')"};foreach($v in @($ast.FindAll({param($n)$n -is [Management.Automation.Language.VariableExpressionAst]},$true))){if([string]::Equals([string]$v.VariablePath.UserPath,'Host',[StringComparison]::OrdinalIgnoreCase)){throw "Staged active 3D runtime references reserved `$Host: $rel line $($v.Extent.StartLineNumber)"}}}
foreach($rel in @('HuymaierConsole.ps1','HuymaierPlatformModels.ps1','HuymaierLivePlatformModels.ps1','HuymaierUser3DModels.ps1','HuymaierLiveModel3D.dll','HuymaierBootstrap.ps1','Install-HuymaierConsole.ps1','Assets\Models\model-map.json','EmulatorPlatforms\platform-registry.json')){[void](NeedFile $rel)}
foreach($rel in @('HuymaierPlatformModels.ps1','HuymaierLivePlatformModels.ps1','HuymaierUser3DModels.ps1')){CheckPs $rel}
foreach($retired in @('HuymaierPlatformAtlas.ps1','HuymaierModelPreviewWorker.exe','Native\HuymaierBuiltInModelGenerator.cs','Assets\Models\platform-models.png','Assets\Models\Live')){if(Test-Path -LiteralPath (Join-Path $StageRoot $retired)){throw "Retired 3D payload survived package: $retired"}}
if(@(Get-ChildItem -LiteralPath $StageRoot -Filter '*.glb' -File -Recurse -ErrorAction SilentlyContinue).Count-ne0){throw 'Normal release candidate unexpectedly bundles GLB files.'}
$core=NeedText 'HuymaierConsole.ps1' @('HUYMAIER_PLATFORM_3D_MODELS_RUNTIME_V2','HUYMAIER_USER_3D_MODELS_RUNTIME_LOAD_V1',"PlatformVisualStyle = 'Icons'",'PlatformIconScale = 100','PlatformModelScale = 100')
$base=NeedText 'HuymaierPlatformModels.ps1' @('HUYMAIER_PLATFORM_PRESENTATION_BASE_V2','HcModelsBaseNewPlatformCard','HcModelsBaseAddPlatformRail')
$live=NeedText 'HuymaierLivePlatformModels.ps1' @('HUYMAIER_LIVE_PLATFORM_3D_HELPERS_V3','HUYMAIER_CONTEXT_AWARE_MODEL_VIEWER_V1','Initialize-HcLiveModelAssembly','Open-HcPlatformModelViewer')
$user=NeedText 'HuymaierUser3DModels.ps1' @('HUYMAIER_USER_3D_MODELS_RUNTIME_V6','HUYMAIER_3D_DUAL_SHELF_RUNTIME_V1','HUYMAIER_3D_TEXTURED_BOUNDED_RESIDENCY_V2',"Join-Path `$script:DataDir '3D Models'",'Test-HcStorefrontPlatform',"Add-Hc3DShelfGroup 'Providers' 'Providers'","Add-Hc3DShelfGroup 'Consoles' 'Consoles'",'maxTextureResidency=4','Textured 3D shelf ready:','Deferred redundant Games 3D shelf rebuild')
foreach($bad in @('$card.Button.Width=470','$card.Button.Height=390','$card.VisualHost.Height=302','textureResidency=3','HcUser3DCardQueue','Set-HcAtlasFallbackVisual')){if($user.Contains($bad)){throw "Retired/oversized staged V5 path survived: $bad"}}
foreach($n in @('$card.Button.Width=$(if($groupFocused){286}else{236})','$card.Button.Height=$(if($groupFocused){178}else{156})','$card.VisualHost.Height=$(if($groupFocused){108}else{92})','$scroll.Height=188')){if(-not$user.Contains($n)){throw "Compact staged V6 shelf contract missing: $n"}}
foreach($n in @("'xbox' {[void]`$names.Add('Xbox App.glb');[void]`$names.Add('Microsoft Xbox App.glb')}",'Resolve-HcShelfModelPath $Platform $Group')){if(-not$user.Contains($n)){throw "Context-aware staged provider resolver missing: $n"}}
if($user.Contains("'xbox' {[void]`$names.Add('Xbox.glb')")){throw 'Staged provider Xbox can resolve to Original Xbox hardware GLB.'}
$res=$user.Substring($user.IndexOf('function Test-Hc3DCardShouldStayResident'),$user.IndexOf('function Set-Hc3DShelfViewFraming')-$user.IndexOf('function Test-Hc3DCardShouldStayResident'));foreach($n in @('Abs([int]$Card.ShelfIndex-$selected)-le1','return ([int]$Card.ShelfIndex-eq$selected)')){if(-not$res.Contains($n)){throw "Staged four-model residency contract missing: $n"}}
$spin=$user.Substring($user.IndexOf('function Start-Hc3DShelfSpinTimer'),$user.IndexOf('function Queue-Hc3DShelfNeighborhood')-$user.IndexOf('function Start-Hc3DShelfSpinTimer'));foreach($n in @('FromMilliseconds(50)','.Rotate(.34,0)','.Rotate(.12,0)',"@('Providers','Consoles')")){if(-not$spin.Contains($n)){throw "Staged V6 turntable missing: $n"}};if($spin.Contains('Render-Page')){throw 'Staged V6 turntable rebuilds Games.'}
$dll=NeedFile 'HuymaierLiveModel3D.dll';$peBytes=[IO.File]::ReadAllBytes($dll);$pe=[BitConverter]::ToInt32($peBytes,0x3C);$machine=[BitConverter]::ToUInt16($peBytes,$pe+4);if($machine-ne0x8664){throw ("HuymaierLiveModel3D.dll is not x64 (0x{0:X4})." -f $machine)}
Add-Type -AssemblyName PresentationFramework,PresentationCore,WindowsBase,System.Xaml,System.Web.Extensions
function New-CheckerPng{$w=8;$h=8;$stride=$w*4;$pixels=New-Object byte[] ($stride*$h);for($y=0;$y-lt$h;$y++){for($x=0;$x-lt$w;$x++){$o=$y*$stride+$x*4;if($x-lt4){$pixels[$o]=24;$pixels[$o+1]=32;$pixels[$o+2]=238}else{$pixels[$o]=238;$pixels[$o+1]=48;$pixels[$o+2]=30};$pixels[$o+3]=255}};$bmp=[Windows.Media.Imaging.BitmapSource]::Create($w,$h,96,96,[Windows.Media.PixelFormats]::Bgra32,$null,$pixels,$stride);$enc=New-Object Windows.Media.Imaging.PngBitmapEncoder;$enc.Frames.Add([Windows.Media.Imaging.BitmapFrame]::Create($bmp));$ms=New-Object IO.MemoryStream;try{$enc.Save($ms);return ,([byte[]]$ms.ToArray())}finally{$ms.Dispose()}}
function New-V6ProbeGlb([string]$Path){$png=New-CheckerPng;$ms=New-Object IO.MemoryStream;$bw=New-Object IO.BinaryWriter($ms);try{foreach($f in @([single]-1,[single](-0.72),[single]0,[single]1,[single](-0.72),[single]0,[single]1,[single](0.72),[single]0,[single]-1,[single](0.72),[single]0)){$bw.Write($f)};foreach($i in 0..3){$bw.Write([single]0);$bw.Write([single]0);$bw.Write([single]1)};foreach($f in @([single]0,[single]0,[single]1,[single]0,[single]1,[single]1,[single]0,[single]1)){$bw.Write($f)};foreach($ix in @([uint16]0,[uint16]1,[uint16]2,[uint16]0,[uint16]2,[uint16]3)){$bw.Write($ix)};$img=[int]$ms.Position;$bw.Write($png);while(($ms.Position%4)-ne0){$bw.Write([byte]0)};$bw.Flush();$bin=[byte[]]$ms.ToArray()}finally{$bw.Dispose();$ms.Dispose()}
$json="{`"asset`":{`"version`":`"2.0`"},`"extensionsUsed`":[`"KHR_texture_transform`",`"KHR_materials_emissive_strength`"],`"scene`":0,`"scenes`":[{`"nodes`":[0]}],`"nodes`":[{`"mesh`":0}],`"meshes`":[{`"primitives`":[{`"attributes`":{`"POSITION`":0,`"NORMAL`":1,`"TEXCOORD_0`":2},`"indices`":3,`"material`":0,`"mode`":4}]}],`"materials`":[{`"doubleSided`":true,`"alphaMode`":`"BLEND`",`"pbrMetallicRoughness`":{`"baseColorFactor`":[1,1,1,.92],`"baseColorTexture`":{`"index`":0,`"texCoord`":0,`"extensions`":{`"KHR_texture_transform`":{`"offset`":[.08,.03],`"scale`":[.84,.92],`"rotation`":.12}}},`"metallicFactor`":0,`"roughnessFactor`":.85},`"emissiveTexture`":{`"index`":0,`"texCoord`":0},`"emissiveFactor`":[.18,.18,.18],`"extensions`":{`"KHR_materials_emissive_strength`":{`"emissiveStrength`":1.5}}}],`"samplers`":[{`"wrapS`":33071,`"wrapT`":33648}],`"textures`":[{`"sampler`":0,`"source`":0}],`"images`":[{`"bufferView`":4,`"mimeType`":`"image/png`"}],`"buffers`":[{`"byteLength`":$($bin.Length)}],`"bufferViews`":[{`"buffer`":0,`"byteOffset`":0,`"byteLength`":48},{`"buffer`":0,`"byteOffset`":48,`"byteLength`":48},{`"buffer`":0,`"byteOffset`":96,`"byteLength`":32},{`"buffer`":0,`"byteOffset`":128,`"byteLength`":12},{`"buffer`":0,`"byteOffset`":$img,`"byteLength`":$($png.Length)}],`"accessors`":[{`"bufferView`":0,`"componentType`":5126,`"count`":4,`"type`":`"VEC3`",`"min`":[-1,-.72,0],`"max`":[1,.72,0]},{`"bufferView`":1,`"componentType`":5126,`"count`":4,`"type`":`"VEC3`"},{`"bufferView`":2,`"componentType`":5126,`"count`":4,`"type`":`"VEC2`"},{`"bufferView`":3,`"componentType`":5123,`"count`":6,`"type`":`"SCALAR`",`"min`":[0],`"max`":[3]}]}";$jb=[Text.Encoding]::UTF8.GetBytes($json);$pad=(4-($jb.Length%4))%4;$jc=New-Object byte[] ($jb.Length+$pad);[Array]::Copy($jb,$jc,$jb.Length);for($i=$jb.Length;$i-lt$jc.Length;$i++){$jc[$i]=0x20};$total=12+8+$jc.Length+8+$bin.Length;$fs=[IO.File]::Create($Path);$out=New-Object IO.BinaryWriter($fs);try{$out.Write([byte[]](0x67,0x6C,0x54,0x46));$out.Write([uint32]2);$out.Write([uint32]$total);$out.Write([uint32]$jc.Length);$out.Write([uint32]0x4E4F534A);$out.Write($jc);$out.Write([uint32]$bin.Length);$out.Write([uint32]0x004E4942);$out.Write($bin)}finally{$out.Dispose();$fs.Dispose()}}
function Get-RenderStats($View,[string]$Label){$w=260;$h=150;$View.Width=$w;$View.Height=$h;$View.Measure((New-Object Windows.Size($w,$h)));$View.Arrange((New-Object Windows.Rect(0,0,$w,$h)));$View.UpdateLayout();$bmp=New-Object Windows.Media.Imaging.RenderTargetBitmap($w,$h,96,96,[Windows.Media.PixelFormats]::Pbgra32);$bmp.Render($View);$stride=$w*4;$pixels=New-Object byte[] ($stride*$h);$bmp.CopyPixels($pixels,$stride,0);$visible=0;$red=0;$blue=0;$edge=0;for($y=0;$y-lt$h;$y++){for($x=0;$x-lt$w;$x++){$o=$y*$stride+$x*4;$b=[int]$pixels[$o];$g=[int]$pixels[$o+1];$r=[int]$pixels[$o+2];$a=[int]$pixels[$o+3];if($a-le12){continue};$visible++;if($r-gt$b+20-and$r-gt$g+15){$red++};if($b-gt$r+20-and$b-gt$g+15){$blue++};if($x-lt2-or$y-lt2-or$x-ge$w-2-or$y-ge$h-2){$edge++}}};if($visible-lt400){throw "$Label rendered only $visible pixels."};if($red-lt25-or$blue-lt25){throw "$Label lost the transformed embedded texture (red=$red blue=$blue visible=$visible)."};Write-Host "$Label visiblePixels=$visible redPixels=$red bluePixels=$blue edgePixels=$edge";[pscustomobject]@{Visible=$visible;Red=$red;Blue=$blue;Edge=$edge}}
Add-Type -Path $dll
$temp=Join-Path ([IO.Path]::GetTempPath()) ('hc-v6-staged-'+[guid]::NewGuid().ToString('N')+'.glb')
try{New-V6ProbeGlb $temp;$view=New-Object HuymaierConsole.Modeling.LiveModelView -ArgumentList @($temp);if([bool]$view.CardMode-or[int]$view.GeometryCount-ne1-or[int]$view.VertexCount-ne4){throw 'Packaged V6 shelf did not enter expected full-texture mode.'};if([int]$view.MaterialCount-lt1-or[int]$view.TextureCount-lt1-or[int]$view.ImageCount-lt1){throw 'Packaged V6 diagnostics lost material/texture/image counts.'};$view.SetScalePercent(70);$a=Get-RenderStats $view 'stagedV6TexturedShelf';if([int]$a.Edge-ne0){throw "Packaged V6 shelf touches edge before rotation: $($a.Edge)"};$yaw=[double]$view.Yaw;$view.Rotate(45,0);$b=Get-RenderStats $view 'stagedV6TexturedShelfRotated';if([math]::Abs([double]$view.Yaw-$yaw)-lt30){throw 'Packaged V6 shelf did not rotate.'};if([int]$b.Edge-ne0){throw "Packaged V6 shelf touches edge after rotation: $($b.Edge)"}}finally{Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue}
$validation=Get-Content -Raw -LiteralPath $ValidationPath -Encoding UTF8|ConvertFrom-Json
$gates=@('platformModelSettingGate','platformModelPersistenceGate','platformModelScaleGate','platformModelMapCoverageGate','platformModelPresentationBaseGate','platformModelHelperOnlyGate','platformModelLiveViewport3DGate','platformModelViewerControlGate','platformModelLiveDllX64Gate','platformModelUserFolderGate','platformModelOriginalNamingGate','platformModelCustomizationOnlyGate','platformModelNoBundledGlbGate','platformModelNoBundledGeneratorGate','platformModelRetiredAtlasGate','platformModelRetiredPreviewWorkerGate','platformModelRetiredPayloadPruneGate','platformModelV6OwnerGate','platformModelDualShelfGate','platformModelProviderConsoleSplitGate','platformModelCompactRealEstateGate','platformModelProviderXboxContextGate','platformModelFourTextureResidencyGate','platformModelFullTextureConstructorGate','platformModelMaterialCompatibilityGate','platformModelTextureTransformGate','platformModelSamplerGate','platformModelAlphaBlendGate','platformModelEmissiveTextureGate','platformModelTextureDiagnosticsGate','platformModelDualShelfTurntableGate','platformModelBackgroundRefreshSuppressionGate','platformModelRotationSafeFramingGate','platformModelSafeRotationFramingPixelGate')
foreach($gate in $gates){$validation|Add-Member -NotePropertyName $gate -NotePropertyValue 'success' -Force;Write-Host ($gate+': success')}
$validation|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $ValidationPath -Encoding UTF8
