param(
    [Parameter(Mandatory=$true)][string]$StageRoot,
    [Parameter(Mandatory=$true)][string]$ValidationPath
)
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'

function NeedFile([string]$rel){$p=Join-Path $StageRoot $rel;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "Staged V5 payload missing: $rel"};$p}
function NeedText([string]$rel,[string[]]$needles){$raw=Get-Content -Raw -LiteralPath (NeedFile $rel) -Encoding UTF8;foreach($n in $needles){if($raw.IndexOf($n,[StringComparison]::Ordinal)-lt0){throw "$rel missing staged V5 contract: $n"}};$raw}
function CheckPs([string]$rel){$p=NeedFile $rel;$t=$null;$e=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($p,[ref]$t,[ref]$e);if(@($e).Count){throw "$rel failed PowerShell 5.1 parse: $(@($e|ForEach-Object{$_.Message}) -join '; ')"};foreach($v in @($ast.FindAll({param($n)$n -is [Management.Automation.Language.VariableExpressionAst]},$true))){if([string]::Equals([string]$v.VariablePath.UserPath,'Host',[StringComparison]::OrdinalIgnoreCase)){throw "Staged active 3D runtime references reserved `$Host: $rel line $($v.Extent.StartLineNumber)"}}}

foreach($rel in @('HuymaierConsole.ps1','HuymaierPlatformModels.ps1','HuymaierLivePlatformModels.ps1','HuymaierUser3DModels.ps1','HuymaierLiveModel3D.dll','HuymaierBootstrap.ps1','Install-HuymaierConsole.ps1','Assets\Models\model-map.json','EmulatorPlatforms\platform-registry.json')){[void](NeedFile $rel)}
foreach($rel in @('HuymaierPlatformModels.ps1','HuymaierLivePlatformModels.ps1','HuymaierUser3DModels.ps1')){CheckPs $rel}
foreach($retired in @('HuymaierPlatformAtlas.ps1','HuymaierModelPreviewWorker.exe','Native\HuymaierBuiltInModelGenerator.cs','Assets\Models\platform-models.png','Assets\Models\Live')){if(Test-Path -LiteralPath (Join-Path $StageRoot $retired)){throw "Retired 3D payload survived package: $retired"}}
if(@(Get-ChildItem -LiteralPath $StageRoot -Filter '*.glb' -File -Recurse -ErrorAction SilentlyContinue).Count-ne0){throw 'Normal release candidate unexpectedly bundles GLB files.'}

$core=NeedText 'HuymaierConsole.ps1' @('HUYMAIER_PLATFORM_3D_MODELS_RUNTIME_V2','HUYMAIER_USER_3D_MODELS_RUNTIME_LOAD_V1',"PlatformVisualStyle = 'Icons'",'PlatformIconScale = 100','PlatformModelScale = 100')
$base=NeedText 'HuymaierPlatformModels.ps1' @('HUYMAIER_PLATFORM_PRESENTATION_BASE_V2','HcModelsBaseNewPlatformCard','HcModelsBaseAddPlatformRail')
$live=NeedText 'HuymaierLivePlatformModels.ps1' @('HUYMAIER_LIVE_PLATFORM_3D_HELPERS_V2','Initialize-HcLiveModelAssembly','Open-HcPlatformModelViewer','X/Square View 3D model')
foreach($bad in @('function New-PlatformCard','function Add-PlatformRail','Set-HcAtlasFallbackVisual')){if($live.Contains($bad)){throw "Helper-only live module still owns presentation: $bad"}}
$user=NeedText 'HuymaierUser3DModels.ps1' @('HUYMAIER_USER_3D_MODELS_RUNTIME_V5','HUYMAIER_3D_SHELF_BOUNDED_RESIDENCY_V1','HuymaierUser3DModelsV5',"Join-Path `$script:DataDir '3D Models'",'New-Hc3DShelfLiveModelView','Trim-Hc3DShelfResidency','Update-Hc3DShelfLoadQueue','Start-Hc3DShelfSpinTimer','Queue-Hc3DShelfNeighborhood','Center-Hc3DShelfSelection','Update-Hc3DShelfSelection','Add-Hc3DPlatformShelf','Textured 3D shelf ready:','Deferred redundant Games 3D shelf rebuild','textureResidency=3','3D shelf model size','Controller UI dispatch failed:')
foreach($bad in @('HcUser3DCardQueue','Queue-HcUser3DCard','New-HcUserCardLiveModelView','HcLiveModelCard','Set-HcAtlasFallbackVisual')){if($user.Contains($bad)){throw "Retired V4 per-card path survived staged V5: $bad"}}

# Full texture loader, safe framing and shelf focus boundary.
$vs=$user.IndexOf('function New-Hc3DShelfLiveModelView',[StringComparison]::Ordinal);$ve=$user.IndexOf('function Start-Hc3DShelfLoadTimer',$vs,[StringComparison]::Ordinal);$scope=$user.Substring($vs,$ve-$vs);if(-not$scope.Contains('New-Object HuymaierConsole.Modeling.LiveModelView -ArgumentList @($Path)')-or$scope.Contains('@($Path,$true)')){throw 'Staged V5 shelf is not using the original textured LiveModelView constructor.'}
$fs=$user.IndexOf('function Set-Hc3DShelfViewFraming',[StringComparison]::Ordinal);$fe=$vs;$frame=$user.Substring($fs,$fe-$fs);foreach($n in @('$safeScale=55.0','150.0)*15.0','SetScalePercent($safeScale)')){if(-not$frame.Contains($n)){throw "Staged V5 rotation-safe framing missing: $n"}}
$is=$user.IndexOf('function Get-Hc3DShelfSelectedLocalIndex',[StringComparison]::Ordinal);$ie=$fs;$idxScope=$user.Substring($is,$ie-$is);if(-not$idxScope.Contains('if($index-lt0-or$index-ge$script:Hc3DShelfCards.Count){return -1}')){throw 'Staged V5 shelf focus boundary is missing.'};if($idxScope.Contains('[math]::Max')-or$idxScope.Contains('[math]::Min')){throw 'Staged V5 shelf focus still clamps non-shelf actions.'}

# At most selected + immediate left/right are live textured models.
$ts=$user.IndexOf('function Trim-Hc3DShelfResidency',[StringComparison]::Ordinal);$te=$user.IndexOf('function Update-Hc3DShelfLoadQueue',$ts,[StringComparison]::Ordinal);$trim=$user.Substring($ts,$te-$ts);foreach($n in @('Abs([int]$request.Card.Index-$Selected)-le1','Abs([int]$card.Index-$Selected)-le1','$card.VisualHost.Child=$card.Icon','$card.View=$null')){if(-not$trim.Contains($n)){throw "Staged bounded residency missing: $n"}}
$qe=$user.IndexOf('function Start-Hc3DShelfSpinTimer',$te,[StringComparison]::Ordinal);$queue=$user.Substring($te,$qe-$te);foreach($n in @('Abs([int]$card.Index-$selected)-gt1','$card.VisualHost.Child=$view','$card.View=$view','$card.VisualHost.Child=$card.Icon')){if(-not$queue.Contains($n)){throw "Staged lazy texture loader missing: $n"}};if($queue.Contains('Render-Page')){throw 'Staged lazy texture loader rebuilds Games.'}
$ns=$user.IndexOf('function Queue-Hc3DShelfNeighborhood',[StringComparison]::Ordinal);$ne=$user.IndexOf('function Center-Hc3DShelfSelection',$ns,[StringComparison]::Ordinal);$near=$user.Substring($ns,$ne-$ns);if(-not$near.Contains('@(0,1,-1)')){throw 'Staged V5 texture neighborhood is not bounded to three models.'}

# Turntable transform only.
$ss=$user.IndexOf('function Start-Hc3DShelfSpinTimer',[StringComparison]::Ordinal);$se=$ns;$spin=$user.Substring($ss,$se-$ss);foreach($n in @('FromMilliseconds(50)','.Rotate(.60,0)','.Rotate(.22,0)','$distance-eq1')){if(-not$spin.Contains($n)){throw "Staged turntable contract missing: $n"}};if($spin.Contains('Render-Page')){throw 'Staged turntable animation rebuilds Games.'}
$selS=$user.IndexOf('function Update-Hc3DShelfSelection',[StringComparison]::Ordinal);$selE=$user.IndexOf('function New-Hc3DShelfCard',$selS,[StringComparison]::Ordinal);$sel=$user.Substring($selS,$selE-$selS);foreach($n in @('Trim-Hc3DShelfResidency $selected','$card.Button.Width=470','$card.Button.Height=390','$card.VisualHost.Height=302','Center-Hc3DShelfSelection')){if(-not$sel.Contains($n)){throw "Staged centered shelf contract missing: $n"}}
$rs=$user.IndexOf('function Render-Page',[StringComparison]::Ordinal);$re=$user.IndexOf('function Add-HcPlatformPresentationSettings',$rs,[StringComparison]::Ordinal);$render=$user.Substring($rs,$re-$rs);foreach($n in @('$script:Hc3DShelfMounted',"`$script:SelectedTab-eq1",'Deferred redundant Games 3D shelf rebuild','Reset-Hc3DShelfRuntime','HcUserModelsBaseRenderPage')){if(-not$render.Contains($n)){throw "Staged background-refresh suppression missing: $n"}}

$expected=@('Arcade.glb','Atari 2600.glb','Atari Lynx.glb','Epic Games.glb','Neo Geo Pocket Color.glb','Neo Geo.glb','Nintendo 3DS.glb','Nintendo 64.glb','Nintendo DS.glb','Nintendo DSI.glb','Nintendo Entertainment System.glb','Nintendo Game Boy Advance.glb','Nintendo Game Boy Color.glb','Nintendo Game Boy.glb','Nintendo GameCube.glb','Nintendo Switch.glb','Nintendo Wii U.glb','Nintendo Wii.glb','PlayStation 2.glb','PlayStation 3.glb','Playstation 4.glb','Playstation 5.glb','Sega Dreamcast.glb','Sega Genesis.glb','Sega Logo.glb','Sega Master System.glb','Sega Mega Drive.glb','Sega Saturn.glb','Sony Playstation Portable.glb','Sony Playstation Vita.glb','Sony PlayStation.glb','Steam.glb','Super Nintendo Entertainment System.glb','XBOX 360.glb','Xbox One.glb','Xbox.glb');if($expected.Count-ne36){throw 'Original model filename contract changed.'};foreach($name in $expected){if(-not$user.Contains("'$name'")){throw "Staged model naming guide missing: $name"}}

# DLL must be x64.
$dll=NeedFile 'HuymaierLiveModel3D.dll';$peBytes=[IO.File]::ReadAllBytes($dll);$pe=[BitConverter]::ToInt32($peBytes,0x3C);$machine=[BitConverter]::ToUInt16($peBytes,$pe+4);if($machine-ne0x8664){throw ("HuymaierLiveModel3D.dll is not x64 (0x{0:X4})." -f $machine)}

# Create a real embedded-texture GLB and prove packaged DLL paints both texture
# colors with zero edge pixels before/after rotation at V5's max occupancy.
Add-Type -AssemblyName PresentationFramework,PresentationCore,WindowsBase,System.Xaml,System.Web.Extensions
function NewCheckerPng{$w=8;$h=8;$stride=$w*4;$px=New-Object byte[] ($stride*$h);for($y=0;$y-lt$h;$y++){for($x=0;$x-lt$w;$x++){$o=$y*$stride+$x*4;if($x-lt4){$px[$o]=24;$px[$o+1]=32;$px[$o+2]=238}else{$px[$o]=238;$px[$o+1]=48;$px[$o+2]=30};$px[$o+3]=255}};$bmp=[Windows.Media.Imaging.BitmapSource]::Create($w,$h,96,96,[Windows.Media.PixelFormats]::Bgra32,$null,$px,$stride);$enc=New-Object Windows.Media.Imaging.PngBitmapEncoder;$enc.Frames.Add([Windows.Media.Imaging.BitmapFrame]::Create($bmp));$ms=New-Object IO.MemoryStream;try{$enc.Save($ms);return ,([byte[]]$ms.ToArray())}finally{$ms.Dispose()}}
function NewProbeGlb([string]$Path){$png=NewCheckerPng;$ms=New-Object IO.MemoryStream;$bw=New-Object IO.BinaryWriter($ms);try{foreach($f in @([single]-1,[single]-1,[single]0,[single]1,[single]-1,[single]0,[single]1,[single]1,[single]0,[single]-1,[single]1,[single]0)){$bw.Write($f)};foreach($i in 0..3){$bw.Write([single]0);$bw.Write([single]0);$bw.Write([single]1)};foreach($f in @([single]0,[single]0,[single]1,[single]0,[single]1,[single]1,[single]0,[single]1)){$bw.Write($f)};foreach($ix in @([uint16]0,[uint16]1,[uint16]2,[uint16]0,[uint16]2,[uint16]3)){$bw.Write($ix)};$img=[int]$ms.Position;$bw.Write($png);while(($ms.Position%4)-ne0){$bw.Write([byte]0)};$bw.Flush();$bin=[byte[]]$ms.ToArray()}finally{$bw.Dispose();$ms.Dispose()};$json="{`"asset`":{`"version`":`"2.0`"},`"scene`":0,`"scenes`":[{`"nodes`":[0]}],`"nodes`":[{`"mesh`":0}],`"meshes`":[{`"primitives`":[{`"attributes`":{`"POSITION`":0,`"NORMAL`":1,`"TEXCOORD_0`":2},`"indices`":3,`"material`":0,`"mode`":4}]}],`"materials`":[{`"doubleSided`":true,`"pbrMetallicRoughness`":{`"baseColorFactor`":[1,1,1,1],`"baseColorTexture`":{`"index`":0,`"texCoord`":0},`"metallicFactor`":0,`"roughnessFactor`":1}}],`"textures`":[{`"source`":0}],`"images`":[{`"bufferView`":4,`"mimeType`":`"image/png`"}],`"buffers`":[{`"byteLength`":$($bin.Length)}],`"bufferViews`":[{`"buffer`":0,`"byteOffset`":0,`"byteLength`":48},{`"buffer`":0,`"byteOffset`":48,`"byteLength`":48},{`"buffer`":0,`"byteOffset`":96,`"byteLength`":32},{`"buffer`":0,`"byteOffset`":128,`"byteLength`":12},{`"buffer`":0,`"byteOffset`":$img,`"byteLength`":$($png.Length)}],`"accessors`":[{`"bufferView`":0,`"componentType`":5126,`"count`":4,`"type`":`"VEC3`",`"min`":[-1,-1,0],`"max`":[1,1,0]},{`"bufferView`":1,`"componentType`":5126,`"count`":4,`"type`":`"VEC3`"},{`"bufferView`":2,`"componentType`":5126,`"count`":4,`"type`":`"VEC2`"},{`"bufferView`":3,`"componentType`":5123,`"count`":6,`"type`":`"SCALAR`",`"min`":[0],`"max`":[3]}]}";$jb=[Text.Encoding]::UTF8.GetBytes($json);$pad=(4-($jb.Length%4))%4;$jc=New-Object byte[] ($jb.Length+$pad);[Array]::Copy($jb,$jc,$jb.Length);for($i=$jb.Length;$i-lt$jc.Length;$i++){$jc[$i]=0x20};$total=12+8+$jc.Length+8+$bin.Length;$fs=[IO.File]::Create($Path);$out=New-Object IO.BinaryWriter($fs);try{$out.Write([byte[]](0x67,0x6C,0x54,0x46));$out.Write([uint32]2);$out.Write([uint32]$total);$out.Write([uint32]$jc.Length);$out.Write([uint32]0x4E4F534A);$out.Write($jc);$out.Write([uint32]$bin.Length);$out.Write([uint32]0x004E4942);$out.Write($bin)}finally{$out.Dispose();$fs.Dispose()}}
function Stats($View,[string]$Label){$w=220;$h=180;$View.Width=$w;$View.Height=$h;$View.Measure((New-Object Windows.Size($w,$h)));$View.Arrange((New-Object Windows.Rect(0,0,$w,$h)));$View.UpdateLayout();$bmp=New-Object Windows.Media.Imaging.RenderTargetBitmap($w,$h,96,96,[Windows.Media.PixelFormats]::Pbgra32);$bmp.Render($View);$stride=$w*4;$px=New-Object byte[] ($stride*$h);$bmp.CopyPixels($px,$stride,0);$vis=0;$red=0;$blue=0;$edge=0;for($y=0;$y-lt$h;$y++){for($x=0;$x-lt$w;$x++){$o=$y*$stride+$x*4;$b=[int]$px[$o];$g=[int]$px[$o+1];$r=[int]$px[$o+2];$a=[int]$px[$o+3];if($a-le12){continue};$vis++;if($r-gt$b+25-and$r-gt$g+18){$red++};if($b-gt$r+25-and$b-gt$g+18){$blue++};if($x-lt2-or$y-lt2-or$x-ge$w-2-or$y-ge$h-2){$edge++}}};if($vis-lt500-or$red-lt40-or$blue-lt40){throw "$Label failed texture pixel gate: visible=$vis red=$red blue=$blue"};Write-Host "$Label visiblePixels=$vis redPixels=$red bluePixels=$blue edgePixels=$edge";[pscustomobject]@{Edge=$edge}}
Add-Type -Path $dll;$temp=Join-Path ([IO.Path]::GetTempPath()) ('hc-v5-staged-'+[guid]::NewGuid().ToString('N')+'.glb');try{NewProbeGlb $temp;$view=New-Object HuymaierConsole.Modeling.LiveModelView -ArgumentList @($temp);if([bool]$view.CardMode-or[int]$view.GeometryCount-ne1-or[int]$view.VertexCount-ne4){throw 'Packaged V5 textured shelf did not enter expected full-texture mode.'};$view.SetScalePercent(70);$a=Stats $view 'stagedTexturedShelf';if([int]$a.Edge-ne0){throw "Packaged V5 shelf touches edge before rotation: $($a.Edge)"};$yaw=[double]$view.Yaw;$view.Rotate(35,0);$b=Stats $view 'stagedTexturedShelfRotated';if([math]::Abs([double]$view.Yaw-$yaw)-lt20){throw 'Packaged V5 shelf did not rotate.'};if([int]$b.Edge-ne0){throw "Packaged V5 shelf touches edge after rotation: $($b.Edge)"}}finally{Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue}

$validation=Get-Content -Raw -LiteralPath $ValidationPath -Encoding UTF8|ConvertFrom-Json
$gates=@('platformModelSettingGate','platformModelPersistenceGate','platformModelScaleGate','platformModelMapCoverageGate','platformModelPresentationBaseGate','platformModelHelperOnlyGate','platformModelLiveViewport3DGate','platformModelViewerControlGate','platformModelLiveDllX64Gate','platformModelUserFolderGate','platformModelOriginalNamingGate','platformModelCustomizationOnlyGate','platformModelTexturedShelfGate','platformModelBoundedTextureResidencyGate','platformModelShelfFocusBoundaryGate','platformModelLazyNeighborhoodGate','platformModelTurntableAnimationGate','platformModelCenteredSelectionGate','platformModelSafeFramingGate','platformModelBackgroundRefreshSuppressionGate','platformModelPresentationOwnershipGate','platformModelSettingsActionOwnershipGate','platformModelControllerUiBoundaryGate','platformModelReservedHostVariableGate','platformModelNoBundledGlbGate','platformModelNoBundledGeneratorGate','platformModelRetiredAtlasGate','platformModelRetiredPreviewWorkerGate','platformModelRetiredPayloadPruneGate','platformModelTexturedShelfPixelGate','platformModelTexturedShelfTextureGate','platformModelTexturedShelfRotationGate','platformModelSafeRotationFramingPixelGate')
foreach($gate in $gates){$validation|Add-Member -NotePropertyName $gate -NotePropertyValue 'success' -Force;Write-Host ($gate+': success')}
$validation|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $ValidationPath -Encoding UTF8
